version: '2'
services:
    example_jhipster-app:
        image: example_jhipster
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://example_jhipster-mysql:3306/example_jhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://example_jhipster-elasticsearch:9200
        ports:
            - 8080:8080
    example_jhipster-mysql:
        extends:
            file: mysql.yml
            service: example_jhipster-mysql
    example_jhipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: example_jhipster-elasticsearch
